name: Integrate Libraries

on:
  push:
    branches:
      - main  # Change this to the appropriate branch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone class library repository
      run: |
        cd D:/a
        git clone https://github.com/IsraelJuniorSL/TesteAction.Application.git
        dir
        
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build libraries
      run: |
        cd D:/a/TesteAction.Application
        dir
        nuget restore
        msbuild /p:Configuration=Release
      shell: cmd

    - name: Copy DLLs to WebForms project
      run: |
        cp D:/a/TesteAction.Application/TesteAction.Application/bin/Release/*.dll D:/a/TesteAction.Web/TesteAction.Web/bin/Release

    - name: Build WebForms application
      run: |
        cd   cd D:/a/TesteAction.Web
        msbuild /p:Configuration=Release
      shell: cmd
