name: Integrate Libraries

on:
  push:
    branches:
      - main  # Change this to the appropriate branch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.7.2'

    - name: Build libraries
      run: |
        cd https://github.com/IsraelJuniorSL/TesteAction.Application
        nuget restore
        msbuild /p:Configuration=Release

    - name: Copy DLLs to WebForms project
      run: |
        cp https://github.com/IsraelJuniorSL/TesteAction.Application/bin/Release/*.dll https://github.com/IsraelJuniorSL/TesteAction.Web

    - name: Build WebForms application
      run: |
        cd https://github.com/IsraelJuniorSL/TesteAction.Web
        msbuild /p:Configuration=Release
