name: Integrate Libraries

on:
  push:
    branches:
      - main  # Change this to the appropriate branch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone class library repository
      run: |
        git clone https://github.com/IsraelJuniorSL/TesteAction.Application.git

    - name: Build libraries
      run: |
        cd TesteAction.Application
        nuget restore
        msbuild /p:Configuration=Release

    - name: Copy DLLs to WebForms project
      run: |
        cd ../
        cp TesteAction.Application/bin/Release/*.dll TesteAction.Web/bin/Release

    - name: Build WebForms application
      run: |
        cd https://github.com/IsraelJuniorSL/TesteAction.Web
        msbuild /p:Configuration=Release
